# Generated by Django 6.0.2 on 2026-02-15 09:08

import django.core.validators
import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('prix', models.PositiveIntegerField(help_text='Prix en FCFA (0 pour les dons)')),
                ('categorie', models.CharField(choices=[('Livres', 'Livres'), ('Electronique', 'Électronique'), ('Vetements', 'Vêtements'), ('Sports', 'Sports'), ('Musique', 'Musique'), ('Accessoires', 'Accessoires'), ('Autres', 'Autres')], max_length=20)),
                ('condition', models.CharField(choices=[('neuf', 'Neuf'), ('tres_bon', 'Très bon état'), ('bon', 'Bon état'), ('moyen', 'État moyen'), ('reparer', 'À réparer')], default='bon', max_length=10)),
                ('type_transaction', models.CharField(choices=[('vendre', 'À vendre'), ('echanger', 'À échanger'), ('don', 'Don')], default='vendre', max_length=10)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('vendu', 'Vendu / Échangé'), ('retire', 'Retiré')], default='disponible', max_length=12)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=marketplace.models.article_photo_path)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.article')),
            ],
            options={
                'verbose_name': "Photo d'article",
                'verbose_name_plural': "Photos d'articles",
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(help_text="Nom de l'article souhaité", max_length=200)),
                ('categorie', models.CharField(choices=[('Livres', 'Livres'), ('Electronique', 'Électronique'), ('Vetements', 'Vêtements'), ('Sports', 'Sports'), ('Musique', 'Musique'), ('Accessoires', 'Accessoires'), ('Autres', 'Autres')], max_length=20)),
                ('description', models.TextField(help_text="Décrivez l'article que vous recherchez")),
                ('budget_max', models.PositiveIntegerField(default=0, help_text='Budget max en FCFA (0 = flexible)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=12)),
                ('reponse_admin', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'article",
                'verbose_name_plural': "Demandes d'articles",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_livre', models.CharField(help_text='Titre du livre que vous proposez', max_length=150)),
                ('description_livre', models.TextField(blank=True, help_text='Description de votre livre')),
                ('photo_livre', models.ImageField(help_text='Photo de votre livre (obligatoire)', upload_to=marketplace.models.echange_photo_path)),
                ('message', models.TextField(blank=True, help_text='Message au vendeur')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_propose', models.ForeignKey(help_text='Le livre mis en échange par le vendeur', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to='marketplace.article')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_echange_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'échange",
                'verbose_name_plural': "Demandes d'échange",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.article')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['categorie', 'statut'], name='marketplace_categor_659edc_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['vendeur', 'statut'], name='marketplace_vendeur_b0a573_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['type_transaction'], name='marketplace_type_tr_8499e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='demandeechange',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'en_attente')), fields=('article_propose', 'demandeur'), name='unique_demande_active'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('vendeur', 'acheteur', 'article')},
        ),
    ]
