# Generated by Django 6.0.2 on 2026-02-20 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='accepte_crown',
            field=models.BooleanField(default=True, help_text='Cochez si vous acceptez les paiements en Crown'),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_crown',
            field=models.PositiveIntegerField(blank=True, help_text="Prix de l'article en Crown (1 Crown = 1 FCFA)", null=True),
        ),
        migrations.CreateModel(
            name='CrownOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_crown', models.PositiveIntegerField(help_text='Montant en Crown')),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('paid', '💰 Payée'), ('confirmed', '✅ Confirmée'), ('shipped', '📦 Expédiée'), ('completed', '🎉 Terminée'), ('cancelled', '❌ Annulée'), ('refunded', '↩️ Remboursée')], default='pending', max_length=15)),
                ('shipping_address', models.TextField(blank=True)),
                ('shipping_phone', models.CharField(blank=True, max_length=20)),
                ('buyer_notes', models.TextField(blank=True, help_text="Notes de l'acheteur")),
                ('seller_notes', models.TextField(blank=True, help_text='Notes du vendeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crown_orders', to='marketplace.article')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crown_orders_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crown_orders_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande Crown',
                'verbose_name_plural': 'Commandes Crown',
                'ordering': ['-created_at'],
            },
        ),
    ]
