# Generated by Django 6.0.2 on 2026-02-16 17:00

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='✅', help_text='Emoji ou texte court affiché à côté du nom', max_length=10)),
                ('couleur', models.CharField(choices=[('blue', '🔵 Bleu (vérifié)'), ('gold', '🟡 Or (premium)'), ('green', '🟢 Vert (fiable)'), ('purple', '🟣 Violet (élite)')], default='blue', max_length=10)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Image optionnelle (PNG transparent recommandé)', max_length=255, null=True, verbose_name='image')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, help_text='Format : 6XXXXXXXX', max_length=20)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, choices=[('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('Est', 'Est'), ('Extreme-Nord', 'Extrême-Nord'), ('Littoral', 'Littoral'), ('Nord', 'Nord'), ('Nord-Ouest', 'Nord-Ouest'), ('Ouest', 'Ouest'), ('Sud', 'Sud'), ('Sud-Ouest', 'Sud-Ouest')], max_length=20)),
                ('photo_profil', cloudinary.models.CloudinaryField(blank=True, help_text="Photo de profil de l'utilisateur", max_length=255, null=True, verbose_name='image')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('est_certifie', models.BooleanField(default=False, help_text="Coché par l'admin après vérification")),
                ('date_certification', models.DateTimeField(blank=True, null=True)),
                ('note_moyenne', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('nb_ventes', models.PositiveIntegerField(default=0)),
                ('nb_echanges', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('badge', models.ForeignKey(blank=True, help_text='Badge attribué à cet utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='accounts.badge')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DemandeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Pourquoi souhaitez-vous être certifié ?')),
                ('document', models.FileField(blank=True, help_text='Document justificatif (CNI, etc.)', null=True, upload_to='verifications/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=15)),
                ('reponse_admin', models.TextField(blank=True, help_text="Réponse/Note de l'admin")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de verification',
                'verbose_name_plural': 'Demandes de verification',
                'db_table': 'accounts_demandeverification',
                'ordering': ['-created_at'],
            },
        ),
    ]
