# Generated by Django 6.0.2 on 2026-02-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de verification', 'verbose_name_plural': 'Demandes de verification'},
        ),
        migrations.AlterModelTable(
            name='demandeverification',
            table='accounts_demandeverification',
        ),
    ]
