# Generated by Django 6.0.2 on 2026-02-20 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrownPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fcfa', models.PositiveIntegerField(help_text='Montant déposé en FCFA')),
                ('payment_proof', models.ImageField(blank=True, help_text="Capture d'écran du paiement Mobile Money", null=True, upload_to='crown_proofs/')),
                ('message', models.TextField(blank=True, help_text="Message à l'admin")),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('approved', '✅ Approuvée'), ('rejected', '❌ Rejetée')], default='pending', max_length=10)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_crown_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crown_purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'achat Crown",
                'verbose_name_plural': "Demandes d'achat Crown",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrownWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, help_text='Solde en Crown')),
                ('balance_blocked', models.PositiveIntegerField(default=0, help_text='Crown bloqués (en attente de validation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crown_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille Crown',
                'verbose_name_plural': 'Portefeuilles Crown',
            },
        ),
        migrations.CreateModel(
            name='CrownTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', '💰 Crédit (achat)'), ('debit', '💸 Débit (paiement)'), ('block', '🔒 Blocage'), ('release', '✅ Libération'), ('refund', '↩️ Remboursement')], max_length=10)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complétée'), ('cancelled', 'Annulée')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.article')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.crownwallet')),
            ],
            options={
                'verbose_name': 'Transaction Crown',
                'verbose_name_plural': 'Transactions Crown',
                'ordering': ['-created_at'],
            },
        ),
    ]
