# Generated by Django 6.0.2 on 2026-02-20 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_crownpurchaserequest_crownwallet_crowntransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrownWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_crown', models.PositiveIntegerField(help_text='Montant en Crown à retirer')),
                ('phone_number', models.CharField(help_text='Numéro Mobile Money', max_length=20)),
                ('operator', models.CharField(choices=[('mtn', '📱 MTN Mobile Money'), ('orange', '🍊 Orange Money')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('approved', '✅ Approuvée'), ('rejected', '❌ Rejetée')], default='pending', max_length=10)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdraw_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crown_withdraw_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de retrait Crown',
                'verbose_name_plural': 'Demandes de retrait Crown',
                'ordering': ['-created_at'],
            },
        ),
    ]
